### ISSUE TITLE
How to cite your work? PMID =?

### ISSUE THREAD

**Issue by zhenyisong** [SciLifeLab/NGI-smRNAseq#21]
We have recently completed a simple project on human next-generation data analysis. And in the pipeline, we used the small RNA/ mRNA/ChIP QC pipelines from your Github account. I googled the SciLifeLab projects, there seems no published paper on your work. How can I show my respect to your work?

**Comment by ewels** [comment]
Hi @zhenyisong,

Congratulations on getting your project completed so quickly! It's great that you were able to use our pipelines, and thanks for your help with debugging them (the ChIP pipeline docker issues especially).

As you say, the pipelines aren't currently published (we are thinking of putting a paper together but it will probably be a while yet). If you could cite the GitHub URLs for each pipeline then that should be sufficient. It may be worth noting the git commit hash of the version that you used in your methods so that people know which version of the pipelines you used as we haven't started using release tags on these two pipelines yet.

Many thanks, and let me know if we can be of any further help,

Phil
